// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using protostream.Models;

namespace protostream.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220117212137_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("protostream.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("audienceScore");

                    b.Property<string>("film");

                    b.Property<string>("genre");

                    b.Property<string>("leadStudio");

                    b.Property<decimal>("profitability");

                    b.Property<byte>("rottenTomatoes");

                    b.Property<decimal>("worldwideGross");

                    b.Property<ushort>("year");

                    b.HasKey("id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
